const MAX_TIME_STAMP_DIFF = 10 * 60 * 1000
const NONCE_CACHE_TIME = MAX_TIME_STAMP_DIFF * 2
const TIMESTAMP_LEN = 13
const COLLECTION_NAME = 'kms_appid_info'
const CMK_EFFECTIVE_DURATION = 1 * 365 * 24 * 60 * 60 * 1000
const CMK_LOOP_CLEAR_TIME = 24 * 60 * 60 * 1000
const CMK_EXPIRE_TIME_EXPAND = 10 * 24 * 60 * 60 * 1000
const CMK_LOOP_CLEAR_EXECUTION_TIME = 3
const KEYID_SECRET_MANAGER_DEFAULT_CMK = 'sysDftCMK'

module.exports = {
  MAX_TIME_STAMP_DIFF,
  NONCE_CACHE_TIME,
  TIMESTAMP_LEN,
  COLLECTION_NAME,
  CMK_EFFECTIVE_DURATION,
  CMK_LOOP_CLEAR_TIME,
  CMK_EXPIRE_TIME_EXPAND,
  CMK_LOOP_CLEAR_EXECUTION_TIME,
  KEYID_SECRET_MANAGER_DEFAULT_CMK,
}
