const MAX_TIME_STAMP_DIFF = 10 * 60 * 1000
const NONCE_CACHE_TIME = MAX_TIME_STAMP_DIFF * 2
const TIMESTAMP_LEN = 13
const COLLECTION_NAME = 'kms_appid_info'

module.exports = {
  MAX_TIME_STAMP_DIFF,
  NONCE_CACHE_TIME,
  TIMESTAMP_LEN,
  COLLECTION_NAME,
}
