#ifndef EHSM_DKEYCACHE_AUTO_VERSION_H
#define EHSM_DKEYCACHE_AUTO_VERSION_H
#define EHSM_VERSION "0.3.2"
#define EHSM_DATE "2023.01.14  0:04"
#define EHSM_GIT_SHA "fd59274"
#endif //EHSM_DKEYCACHE_AUTO_VERSION_H
