version: "3.9"
services:
  # CouchDB service
  couchdb:
    container_name: c_couchdb
    image: couchdb:3.2
    ports:
      - "${COUCHDB_PORT}:5984"
    volumes:
      - /opt/couchdb/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

  # eHSM Base Images
  #   just for build a base image.
  ehsm_base:
    container_name: c_ehsm_base
    build: 
      context: .
      dockerfile: ${DOCKER_FILE}
      args:
       http_proxy: ${http_proxy}
       https_proxy: ${http_proxy}
       TAG_VERSION: ${EHSM_VERSION_STR}
    image: "${DOCKER_REPO}${DOCKER_REPO:+/}${IMAGE_NAME_EHSM_BASE}:${EHSM_VERSION_STR}"

  # eHSM Domain Key Server service
  dkeyserver:
    container_name: c_dkeyserver
    build: 
      context: dkeyserver
      args:
       IMAGE_NAME_EHSM_BASE: ${DOCKER_REPO}${DOCKER_REPO:+/}${IMAGE_NAME_EHSM_BASE}
       EHSM_VERSION_STR: ${EHSM_VERSION_STR}
    image: "${DOCKER_REPO}${DOCKER_REPO:+/}ehsm_dkeyserver-dev:${EHSM_VERSION_STR}"
    ports:
      - "${DKEYSERVER_PORT}:8888"
    volumes:
      - /var/run/aesmd:/var/run/aesmd
      - ${EHSM_RUNTIME_FOLDER:-/var/run/ehsm}:/var/run/ehsm
      - ${EHSM_LOCAL_DATA_FOLDER:-/var/local/ehsm}:/var/local/ehsm
      - ${EHSM_LOG_FOLDER:-/var/log/ehsm}:/var/log/ehsm
    environment:
      - PCCS_URL=${PCCS_URL}
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - DKEYSERVER_ROLE=${DKEYSERVER_ROLE}
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    depends_on:
      - ehsm_base

  # eHSM Domain Key Cache service
  dkeycache:
    container_name: c_dkeycache
    build: 
      context: dkeycache
      args:
       IMAGE_NAME_EHSM_BASE: ${DOCKER_REPO}${DOCKER_REPO:+/}${IMAGE_NAME_EHSM_BASE}
       EHSM_VERSION_STR: ${EHSM_VERSION_STR}
    image: "${DOCKER_REPO}${DOCKER_REPO:+/}ehsm_dkeycache-dev:${EHSM_VERSION_STR}"
    volumes:
      - /var/run/aesmd:/var/run/aesmd
      - ${EHSM_RUNTIME_FOLDER:-/var/run/ehsm}:/var/run/ehsm
      - ${EHSM_LOCAL_DATA_FOLDER:-/var/local/ehsm}:/var/local/ehsm
      - ${EHSM_LOG_FOLDER:-/var/log/ehsm}:/var/log/ehsm
    environment:
      - PCCS_URL=${PCCS_URL}
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - DKEYSERVER_IP=${HOST_IP}
      - DKEYSERVER_PORT=${DKEYSERVER_PORT}
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    depends_on:
      - dkeyserver

  pccs:
    container_name: c_pccs
    build: 
      context: pccs
      args:
       http_proxy: ${http_proxy}
       https_proxy: ${http_proxy}
       PCCS_IMAGE_VERSION: ${PCCS_IMAGE_VERSION:-latest}
    profiles: ["pccs"]
    env_file:
      - .env.pccs
    image: "ehsm_pccs:${PCCS_IMAGE_VERSION:-latest}"
    ports:
      - "${PCCS_PORT:-8081}:8081"
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision

  # eHSM KMS service
  ehsmKMS:
    container_name: c_ehsmKMS
    build: 
      context: core
      args:
       http_proxy: ${http_proxy}
       https_proxy: ${http_proxy}
       IMAGE_NAME_EHSM_BASE: ${DOCKER_REPO}${DOCKER_REPO:+/}${IMAGE_NAME_EHSM_BASE}
       EHSM_VERSION_STR: ${EHSM_VERSION_STR}
    image: "${DOCKER_REPO}${DOCKER_REPO:+/}ehsm_kms_service-dev:${EHSM_VERSION_STR}"
    ports:
      - "${KMS_PORT}:9000"
    volumes:
      - /var/run/aesmd:/var/run/aesmd
      - ${EHSM_RUNTIME_FOLDER:-/var/run/ehsm}:/var/run/ehsm
      - ${EHSM_LOCAL_DATA_FOLDER:-/var/local/ehsm}:/var/local/ehsm
      - ${EHSM_LOG_FOLDER:-/var/log/ehsm}:/var/log/ehsm
    environment:
      - PCCS_URL=${PCCS_URL}
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - EHSM_CONFIG_COUCHDB_USERNAME=${COUCHDB_USER}
      - EHSM_CONFIG_COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - EHSM_CONFIG_COUCHDB_PORT=${COUCHDB_PORT}
      - EHSM_CONFIG_COUCHDB_SERVER=${HOST_IP}
      - EHSM_CONFIG_COUCHDB_DB=${COUCHDB_DB}
      - EHSM_CONFIG_OPENSSL_COUNTRYNAME=${OPENSSL_COUNTRYNAME}
      - EHSM_CONFIG_OPENSSL_LOCALITYNAME=${OPENSSL_LOCALITYNAME}
      - EHSM_CONFIG_OPENSSL_ORGANIZATIONNAME=${OPENSSL_ORGANIZATIONNAME}
      - EHSM_CONFIG_OPENSSL_ORGANIZATIONALUNITNAME=${OPENSSL_ORGANIZATIONALUNITNAME}
      - EHSM_CONFIG_OPENSSL_COMMONNAME=${OPENSSL_COMMONNAME}
      - EHSM_CONFIG_OPENSSL_EMAILADDRESS=${OPENSSL_EMAILADDRESS}
      - EHSM_CONFIG_OPENSSL_KEY=${OPENSSL_KEY}
      - EHSM_CONFIG_OPENSSL_CRT=${OPENSSL_CRT}
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    depends_on:
      - dkeycache
