# dkeyserver ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: dkeyserver-configmap
  namespace: dkeyserver
data:
  # you need adjust https://1.2.3.4:8081 to your pccs_url.
  pccs_url: "https://1.2.3.4:8081"

---
# ehsm-kms main dkeyserver
apiVersion: v1
kind: Service
metadata:
  name: dkey-main-service
  namespace: dkeyserver
  labels:
    app: dkey-main
spec:
  ports:
    - name: dkey-main-svc-port
      port: 8888
      targetPort: 8888
  selector:
    app: dkey-main
  clusterIP: None 

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dkey-main
  namespace: dkeyserver
spec:
  selector:
    matchLabels:
      app: dkey-main
  serviceName: "dkey-main-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: dkey-main
    spec:
      volumes:
      - name: dev-enclave
        hostPath:
          path: /dev/sgx/enclave
      - name: dev-provision
        hostPath:
          path: /dev/sgx/provision
      - name: dev-aesmd
        hostPath:
          path: /var/run/aesmd
      - name: runtime-folder
        hostPath:
          path: /var/run/ehsm
      - name: local-data-folder
        hostPath:
          path: /var/local/ehsm
      - name: log-folder
        hostPath:
          path: /var/log/ehsm
      containers:
      - name: dkey-main
        image: intel/dkeyserver:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/sgx/enclave
          name: dev-enclave
        - mountPath: /dev/sgx/provision
          name: dev-provision
        - mountPath: /var/run/aesmd
          name: dev-aesmd
        - mountPath: /var/run/ehsm
          name: runtime-folder
        - mountPath: /var/local/ehsm
          name: local-data-folder
        - mountPath: /var/log/ehsm
          name: log-folder
        readinessProbe:
          tcpSocket:
            port: dkey-main-port
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: dkey-main-port
          initialDelaySeconds: 60
          periodSeconds: 10
        ports: 
        - containerPort: 8888
          name: dkey-main-port
        env:
        - name: PCCS_URL 
          valueFrom:
            configMapKeyRef:
              name: dkeyserver-configmap
              key: pccs_url
        - name: DKEYSERVER_ROLE
          value: "root"
        # you need change TARGET_IP to dkey-provisioning-service's externalIPs.
        - name: TARGET_IP 
          value: "1.2.3.4"
        # you need change TARGET_PORT to dkey-provisioning-service's port.
        - name: TARGET_PORT 
          value: "8888"

---
# ehsm-kms worker dkeyserver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: dkeyserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      volumes:
      - name: dev-enclave
        hostPath:
          path: /dev/sgx/enclave
      - name: dev-provision
        hostPath:
          path: /dev/sgx/provision
      - name: dev-aesmd
        hostPath:
          path: /var/run/aesmd
      - name: runtime-folder
        hostPath:
          path: /var/run/ehsm
      - name: local-data-folder
        hostPath:
          path: /var/local/ehsm
      - name: log-folder
        hostPath:
          path: /var/log/ehsm
      initContainers:
      - name: init-worker
        # this images same the container's image.
        image: intel/dkeyserver:latest
        imagePullPolicy: IfNotPresent
        command: ['sh' , '-c','until nslookup dkey-main-service; do echo waiting for main servier; sleep 5; done;']
      containers:
      - name: worker
        # You need to tag the worker container image with this name on each worker node or change it to point to a docker hub to get the container image.
        image: intel/dkeyserver:latest
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: worker-port
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: worker-port
          initialDelaySeconds: 60
          periodSeconds: 10
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/sgx/enclave
          name: dev-enclave
        - mountPath: /dev/sgx/provision
          name: dev-provision
        - mountPath: /var/run/aesmd
          name: dev-aesmd
        - mountPath: /var/run/ehsm
          name: runtime-folder
        - mountPath: /var/local/ehsm
          name: local-data-folder
        - mountPath: /var/log/ehsm
          name: log-folder
        env:
        - name: PCCS_URL 
          valueFrom:
            configMapKeyRef:
              name: dkeyserver-configmap
              key: pccs_url
        - name: DKEYSERVER_ROLE
          value: "worker"
        # The TARGET_URL is dkey-main-service's url.
        - name: TARGET_URL 
          value: "dkey-main-0.dkey-main-service"
        # The TARGET_PORT is dkey-main-service's port.
        - name: TARGET_PORT
          value: "8888"
        ports:
        - containerPort: 8888
          name: worker-port

---
apiVersion: v1
kind: Service
metadata:
  name: dkey-provisioning-service
  namespace: dkeyserver
spec:
  type: LoadBalancer
  selector:
    app: worker
  ports:
    - name: worker
      protocol: TCP
      # This port is ehsm-kms worker dkeyserver access port,you can change it to what you want.
      port: 8888
      targetPort: 8888
      nodePort: 30010
  sessionAffinity: ClientIP
  externalIPs:
  # This IP is ehsm-kms worker dkeyserver access IP, You need to adjust 1.2.3.4 to the service IP you want to expose
  - 1.2.3.4