from ehsm.serializers.key_management import *
from ehsm.api.base import EHSMBaseClient


class KeyManagementMixin(EHSMBaseClient):
    def get_version(self):
        """
        Query the KMS server version
        """
        resp = self._session.get(
            "", params={"Action": "GetVersion"}, check_credentials=False
        )
        return GetVersionResponse.from_response(resp)

    def enroll(self):
        """
        Obtain a valid access keypair (APPID and APIKey) which is MUST before
        request the public cryptographic APIs
        """
        return self._session.enroll()

    def list_key(self):
        """
        Query all the CMKs generated by the current account
        """
        resp = self._session.post("", params={"Action": "ListKey"})
        return ListKeyResponse.from_response(resp)

    def delete_key(self, keyid: str):
        """
        Delete a specific CMK generated by the current account
        """
        resp = self._session.post(
            "", params={"Action": "DeleteKey"}, data={"keyid": keyid}
        )
        return DeleteKeyResponse.from_response(resp)

    def delete_all_key(self):
        """
        Delete all the CMKs generated by the current account
        """
        resp = self._session.post("", params={"Action": "DeleteAllKey"})
        return DeleteKeyResponse.from_response(resp)

    def enable_key(self, keyid: str):
        """
        Enable a CMK for the current account
        Only when the CMK is enabled, it could be used to perform
        cryptographic operations.
        """
        resp = self._session.post(
            "", params={"Action": "EnableKey"}, data={"keyid": keyid}
        )
        return EnableKeyResponse.from_response(resp)

    def disable_key(self, keyid: str):
        """
        Disables a specified CMK.
        If a CMK is disabled, it can't be used until you re-enable it by the
        EnableKey API.
        """
        resp = self._session.post(
            "", params={"Action": "DisableKey"}, data={"keyid": keyid}
        )
        return DisableKeyResponse.from_response(resp)
